name: Publish to NPM

on:
  release:
    types: [created]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'

    - name: Set version in package.json
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        npm version --allow-same-version --no-git-tag-version ${TAG_NAME#v}

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
